#ifndef PROTOCOL_H
#define PROTOCOL_H
#include <cstdint>
typedef unsigned int uint;

enum ENUM_MSG_TYPE{
    ENUM_MSG_TYPE_MIN = 0,
    ENUM_MSG_TYPE_REGISTER_REQUEST,
    ENUM_MSG_TYPE_REGISTER_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_FIND_USER_REQUEST,
    ENUM_MSG_TYPE_FIND_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_ACCEPT_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_ACCEPT_RESPOND,
    ENUM_MSG_TYPE_REFRESH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_REFRESH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_CHAT_HISTORY_REQUEST,
    ENUM_MSG_TYPE_CHAT_HISTORY_RESPOND,
    ENUM_MSG_TYPE_CREATE_FILE_REQUEST,
    ENUM_MSG_TYPE_CREATE_FILE_RESPOND,
    ENUM_MSG_TYPE_REFRESH_FILE_REQUEST,
    ENUM_MSG_TYPE_REFRESH_FILE_RESPOND,
    ENUM_MSG_TYPE_DELETE_FILE_REQUEST,
    ENUM_MSG_TYPE_DELETE_FILE_RESPOND,
    ENUM_MSG_TYPE_RENAME_FILE_REQUEST,
    ENUM_MSG_TYPE_RENAME_FILE_RESPOND,
    ENUM_MSG_TYPE_MOVE_FILE_REQUEST,
    ENUM_MSG_TYPE_MOVE_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DEAL_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DEAL_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_ACCEPT_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_ACCEPT_RESPOND,
    ENUM_MSG_TYPE_HEARTBEAT_REQUEST,
    ENUM_MSG_TYPE_HEARTBEAT_RESPOND,
    ENUM_MSG_TYPE_MAX = 9999,
};

// Error codes for response messages (placed in caData[0..1])
enum ErrorCode : uint16_t {
    ERR_NONE = 0,
    ERR_AUTH_FAILED,
    ERR_USER_EXISTS,
    ERR_USER_NOT_FOUND,
    ERR_USER_OFFLINE,
    ERR_ALREADY_FRIEND,
    ERR_PATH_UNSAFE,
    ERR_DIR_EXISTS,
    ERR_DIR_CREATE_FAILED,
    ERR_FILE_OPEN_FAILED,
    ERR_FILE_UPLOAD_FAILED,
    ERR_SHARE_FILE_FAILED,
    ERR_DELETE_FAILED,
    ERR_RENAME_FAILED,
    ERR_UNKNOWN = 9999
};

struct PDU{
    uint uiTotalLen;
    uint uiMsgLen;
    uint uiType;
    char caData[64];
    char caMsg[];
};

struct FILE_INFO{
    char name[32];
    uint uiType;
};

#include <memory>

PDU *mkPDU(uint uiMsgLen = 0);

struct PDUDeleter {
    void operator()(PDU* p) const { free(p); }
};
using PDUPtr = std::unique_ptr<PDU, PDUDeleter>;

inline PDUPtr makePDU(uint uiMsgLen = 0) {
    return PDUPtr(mkPDU(uiMsgLen));
}

#endif // PROTOCOL_H
