#ifndef PROTOCOL_H
#define PROTOCOL_H
typedef unsigned int uint;

enum ENUM_MSG_TYPE{
    ENUM_MSG_TYPE_MIN = 0,
    ENUM_MSG_TYPE_REGISE_REQUEST,
    ENUM_MSG_TYPE_REGISE_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_FIND_USER_REQUEST,
    ENUM_MSG_TYPE_FIND_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_CHAT_HISTORY_REQUEST,
    ENUM_MSG_TYPE_CHAT_HISTORY_RESPOND,
    ENUM_MSG_TYPE_CREATE_FILE_REQUEST,
    ENUM_MSG_TYPE_CREATE_FILE_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DELETE_FILE_REQUEST,
    ENUM_MSG_TYPE_DELETE_FILE_RESPOND,
    ENUM_MSG_TYPE_RENAME_FILE_REQUEST,
    ENUM_MSG_TYPE_RENAME_FILE_RESPOND,
    ENUM_MSG_TYPE_MOVE_FILE_REQUEST,
    ENUM_MSG_TYPE_MOVE_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DEAL_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DEAL_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_RESPOND,
    ENUM_MSG_TYPE_MAX = 9999,
};

struct PDU{
    uint uiTotalLen;
    uint uiMsgLen;
    uint uiType;
    char caData[64];
    char caMsg[];
};

struct FILE_INFO{
    char name[32];
    uint uiType;
};

#include <memory>

PDU *mkPDU(uint uiMsgLen = 0);

struct PDUDeleter {
    void operator()(PDU* p) const { free(p); }
};
using PDUPtr = std::unique_ptr<PDU, PDUDeleter>;

inline PDUPtr makePDU(uint uiMsgLen = 0) {
    return PDUPtr(mkPDU(uiMsgLen));
}

#endif // PROTOCOL_H
